### ISSUE TITLE
Nov 20 meeting

### ISSUE THREAD

**Issue by nicolo-ribaudo** [babel/notes#102]
@babel/babel feel free to add items to the agenda!

- [ ] Tests status update (https://github.com/babel/babel/issues/4987, https://github.com/babel/babel/issues/10734) 
- [ ] ESLint migration to the monorepo (https://github.com/babel/babel/issues/10709)
  - [ ] Packages renaming and versioning
  - [ ] Issue migration
- [ ] Print Babel Configuration (https://github.com/babel/babel/issues/10617)
- [ ] Babel 8?
- [ ] Funding status update (https://babeljs.io/blog/2019/11/08/babels-funding-plans, https://github.com/babel/finances (private))
